"""empty message

Revision ID: 002d0dd83eaa
Revises: 04e979e09a5a
Create Date: 2024-09-07 15:56:06.200034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '002d0dd83eaa'
down_revision = '04e979e09a5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dcii_subject', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clearance', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dcii_subject', schema=None) as batch_op:
        batch_op.drop_column('clearance')

    # ### end Alembic commands ###
