"""empty message

Revision ID: 04e979e09a5a
Revises: 0ae3cc2ecf9a
Create Date: 2024-09-07 15:28:26.564828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04e979e09a5a'
down_revision = '0ae3cc2ecf9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dcii_addon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('index', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dcii_addon', schema=None) as batch_op:
        batch_op.drop_column('index')

    # ### end Alembic commands ###
