"""empty message

Revision ID: 0ae3cc2ecf9a
Revises: 2c6894e1cf19
Create Date: 2024-09-07 14:55:02.071041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ae3cc2ecf9a'
down_revision = '2c6894e1cf19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dcii_subject', schema=None) as batch_op:
        batch_op.add_column(sa.Column('index', sa.Integer(), nullable=True))
        batch_op.alter_column('danger',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('probability',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('body',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dcii_subject', schema=None) as batch_op:
        batch_op.alter_column('body',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('probability',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('danger',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('index')

    # ### end Alembic commands ###
