"""empty message

Revision ID: 2c6894e1cf19
Revises: 47d2f2424d7c
Create Date: 2024-09-07 14:22:16.416515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c6894e1cf19'
down_revision = '47d2f2424d7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('clearance',
               existing_type=sa.VARCHAR(length=12),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('clearance',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=12),
               existing_nullable=True)

    # ### end Alembic commands ###
