"""empty message

Revision ID: 866e135675d2
Revises: 
Create Date: 2024-09-08 15:14:32.164141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '866e135675d2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('body')

    # ### end Alembic commands ###
